### ISSUE TITLE
Copy edit

### ISSUE THREAD

**Issue by jrobinson-uk** [raspberrypilearning/getting-started-with-the-sense-hat#1]
@LornaLynch @lauraclay Do either of you have time to Copy edit this resource please. Might be a couple of image changes/additions tomorrow, but largely finished

**Comment by lauraclay** [comment]
Have taken a look, a couple more things need looking at:
- The code has mangled itself so the backticks are visible, and I couldn't seem to fix it
- Check I haven't changed the meaning of line 473. Have assumed it was 'plus or minus 1g' but the symbol had got garbled.

FYI I'm available until 12:30GMT today but will be away in the afternoon/evening.

**Comment by LornaLynch** [comment]
My availability is pretty rubbish today, I'm afraid, but I'll do what I
can.

Lorna Lynch
Copy Editor
Raspberry Pi Foundation
www.raspberrypi.org

**Comment by LornaLynch** [comment]
The formatting looks as if it has got completely messed up towards the end of the document: I haven't touched that yet, so I don't know what's caused it. I'm going to see if I can organise any childcare for later.

**Comment by jrobinson-uk** [comment]
I've now sorted the code formatting and back tick issue.
Laura I can see the +/- symbol (line 476 now).

I've a couple of minor updates to make later (image change) and a bit of text for each example

**Comment by LornaLynch** [comment]
I've had a look and it all seems good to me now. While I was checking I noticed that sensors/movement.md is still missing its final section, but I'm guessing @davidhoness is on top of that.

**Comment by LornaLynch** [comment]
I'll be around again later this afternoon/evening. If there's anything you need, let me know.

Lorna Lynch
Raspberry Pi Foundation
www.raspberrypi.orghttp://www.raspberrypi.org

On 22 May 2015, at 10:46, James Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:

I've now sorted the code formatting and back tick issue.
Laura I can see the +/- symbol (line 476 now).

I've a couple of minor updates to make later (image change) and a bit of text for each example

##

**Comment by lauraclay** [comment]
Thanks so much @LornaLynch and @jrobinson-uk. I was powering through before the first coffee of the day, so I'll blame the code-munging on that!

**Comment by LornaLynch** [comment]
It was all down to James! :)

Lorna Lynch
Raspberry Pi Foundation
www.raspberrypi.orghttp://www.raspberrypi.org

On 22 May 2015, at 12:48, lauraclay <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks so much @LornaLynchhttps://github.com/LornaLynch and @jrobinson-ukhttps://github.com/jrobinson-uk. I was powering through before the first coffee of the day, so I'll blame the code-munging on that!

##
