### ISSUE TITLE
Using .values() doesn't guarantee the order

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/getting-started-with-the-sense-hat#10]
...which means that

``` python
pitch, roll, yaw = sense.get_orientation().values()
```

and

``` python
x, y, z = sense.get_accelerometer_raw().values()
```

are unreliable, as described in https://github.com/RPi-Distro/python-sense-hat/issues/24

**Comment by lurch** [comment]
You've 'fixed' `sense.get_accelerometer_raw().values()` but you didn't fix `sense.get_orientation().values()`.

**Comment by lurch** [comment]
Yup, that looks better :-)

**Comment by MarcScott** [comment]
Closing in on you. You'll soon have no more issues left :smiley:

**Comment by lurch** [comment]
Ah, printable-worksheet.pdf needs to be updated too ;-P
