### ISSUE TITLE
yaw/roll swap typo in getting started worksheet

### ISSUE THREAD

**Issue by kurtgraustein** [raspberrypilearning/getting-started-with-the-sense-hat#18]
The sense.get_orientation() example code block in "Getting Started with the Sense Hat" worksheet has a typo. The roll and yaw variables are swapped in the print command.

`print("pitch={0}, roll={1}, yaw={2}".format(pitch, yaw, roll))`

should be

`print("pitch={0}, roll={1}, yaw={2}".format(pitch, roll, yaw))`

I'm too new to github, branches and pull requests at the moment to fix this myself, but hope to contribute more in time.

**Comment by kurtgraustein** [comment]
The [Sense HAT API Reference](http://pythonhosted.org/sense-hat/api/) shows a couple other ways to avoid this problem altogether:  reference the fields by name in the format string or skip the format string altogether.
 
```
from sense_hat import SenseHat

sense = SenseHat()
orientation = sense.get_orientation()
print("p: {pitch}, r: {roll}, y: {yaw}".format(**orientation))

# alternatives
print(sense.orientation)
```

**Comment by lawsie** [comment]
Cheers @kurtgraustein , we'll sort this out :)

**Comment by lawsie** [comment]
This is now fixed on the markdown file but @MarcScott please could you update the code in the trinket?
