### ISSUE TITLE
Files folder should be "code"

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/getting-started-with-the-sense-hat#3]
The `files` folder needs renaming to `code` and all references from the worksheet updating in one go. Not urgent but should be done at some point.

@LornaLynch if/when you get chance?

**Comment by LornaLynch** [comment]
Sure: I can get to this now.

**Comment by LornaLynch** [comment]
This should be sorted now. If there's anything else I can do, let me know.
