### ISSUE TITLE
Refer to "Sense HAT" not "Astro Pi HAT"

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/getting-started-with-the-sense-hat#6]
I've updated the `hardware.yml` and `hardware.md` files but the worksheet needs updating too.

**Comment by bennuttall** [comment]
Links to the GitHub repo in README, LICENCE, CONTRIBUTING, etc. are all still pointing to astro pi. Not a huge deal but can they be updated too please. And when repos get moved or renamed in future this is something to look out for.

**Comment by LornaLynch** [comment]
I've updated the links, but the reference to the Sense HAT guide in the README still points, of necessity, to this https://github.com/raspberrypilearning/astro-pi-guide 

See #4 in the Astro Pi Guide issues.

**Comment by LornaLynch** [comment]
Just saw your response in the AP guide: I'll leave the URL as it is, but refer to it as the Sense HAT guide for Astro Pi here if that's ok.
