### ISSUE TITLE
Update software installation and all code examples from AstroPi to SenseHat

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/getting-started-with-the-sense-hat#7]
- Software installation is now `sense-hat` - see [docs](https://pythonhosted.org/sense-hat/)
- `from astro_pi import AstroPi` becomes `from sense_hat import SenseHat`
- `ap = AstroPi` becomes `sense = SenseHat`
- `ap.` becomes `sense.`

**Comment by LornaLynch** [comment]
I'm working through this now :)
